"""blog migration

Revision ID: 9e3a96dd9ce9
Revises: 26370b872b23
Create Date: 2019-07-05 14:10:46.045878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e3a96dd9ce9'
down_revision = '26370b872b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('posted', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
